# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TQNMsyAW_w42qZ4gAzm7Ey-P-tzYXFzQ
"""

import cv2
import numpy as np
import torch
import torch.nn.functional as F


def preprocess_canvas(canvas_bgr, model):
    gray = cv2.cvtColor(canvas_bgr, cv2.COLOR_BGR2GRAY)

    if np.count_nonzero(gray) < 500:
        return None

    # Step 3 — Tight bounding box around all non-zero pixels
    points = cv2.findNonZero(gray)
    x, y, w, h = cv2.boundingRect(points)

    canvas_h, canvas_w = gray.shape
    pad_x = int(w * 0.20)
    pad_y = int(h * 0.20)

    x1 = max(x - pad_x, 0)
    y1 = max(y - pad_y, 0)
    x2 = min(x + w + pad_x, canvas_w)
    y2 = min(y + h + pad_y, canvas_h)
    crop = gray[y1:y2, x1:x2]
    _, binary = cv2.threshold(crop, 10, 255, cv2.THRESH_BINARY)

    resized = cv2.resize(binary, (28, 28), interpolation=cv2.INTER_AREA)

    normalized = (resized / 255.0 - 0.1307) / 0.3081

    tensor = torch.FloatTensor(normalized).reshape(1, 1, 28, 28)

    model.eval()
    with torch.no_grad():
        output = model(tensor)

    probabilities = F.softmax(output, dim=1)
    confidence = torch.max(probabilities).item() * 100.0
    digit = torch.argmax(probabilities).item()

    return (digit, confidence)

"""
MNIST CNN Classifier
Architecture: Input (1×28×28) → Conv(32) → Conv(64) → Conv(128) → FC(128) → Output(10)
"""
import torch
import torch.nn as nn
import torch.nn.functional as F

class MNISTConvNet(nn.Module):
    def __init__(self):
        super(MNISTConvNet, self).__init__()

        # Convolutional layers: 1 → 32 → 64 → 128 channels
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)

        # Fully connected layers: 1152 → 128 → 10
        # After 3 pooling operations: 28×28 → 14×14 → 7×7 → 3×3
        self.fc1 = nn.Linear(3 * 3 * 128, 128)
        self.fc2 = nn.Linear(128, 10)

        # Regularization
        self.dropout = nn.Dropout(0.5)

    def forward(self, x):
        # Conv Block 1: (batch, 1, 28, 28) → (batch, 32, 14, 14)
        x = self.pool(F.relu(self.conv1(x)))

        # Conv Block 2: (batch, 32, 14, 14) → (batch, 64, 7, 7)
        x = self.pool(F.relu(self.conv2(x)))

        # Conv Block 3: (batch, 64, 7, 7) → (batch, 128, 3, 3)
        x = self.pool(F.relu(self.conv3(x)))

        # Flatten: (batch, 128, 3, 3) → (batch, 1152)
        x = x.view(x.size(0), -1)

        # Fully connected with dropout
        x = F.relu(self.fc1(x))
        x = self.dropout(x)

        # Output layer (10 classes)
        x = self.fc2(x)
        return x

